# Basic Numpy Arrays

In [1]:
import sys
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 0.5, 1, 1.5, 2])

In [3]:
a[0:]

array([1, 2, 3, 4])

In [5]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [6]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('float64')

In [8]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

# Dimensions and Shapes

In [9]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [10]:
A.shape

(2, 3)

In [11]:
A.ndim

2

In [12]:
A.size

6

In [13]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [14]:
B.shape

(2, 2, 3)

In [15]:
B.ndim

3

In [16]:
B.size

12

In [17]:
# If the shape isn't consistent, it will fall back to regular python objects

In [18]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4]
    ]
])

<ipython-input-18-542efa257820>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  C = np.array([


In [19]:
C.dtype

dtype('O')

In [20]:
C.shape

(2,)

In [21]:
C.size

2

# Indexing and Slicing of Matrices

In [22]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [23]:
A[1]

array([4, 5, 6])

In [24]:
A[1, 0]

4

In [25]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [27]:
A[1] = np.array([10, 10, 10])

In [28]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [29]:
A[2] = 99

In [30]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summery statistics

In [31]:
a = np.array([1, 2, 3, 4])

In [32]:
a.sum()

10

In [33]:
a.mean()

2.5

In [34]:
a.std()

1.118033988749895

In [36]:
a.var()

1.25

In [39]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [40]:
A.sum()

45

In [41]:
A.mean()

5.0

In [42]:
A.std()

2.581988897471611

In [43]:
A.sum(axis=0)

array([12, 15, 18])

In [44]:
A.sum(axis=1)

array([ 6, 15, 24])

In [45]:
A.mean(axis=0)

array([4., 5., 6.])

In [46]:
A.mean(axis=1)

array([2., 5., 8.])

In [47]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [48]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations

In [49]:
a = np.arange(4)

In [51]:
a

array([0, 1, 2, 3])

In [52]:
a + 10

array([10, 11, 12, 13])

In [53]:
a * 10

array([ 0, 10, 20, 30])

In [54]:
a += 100

In [55]:
a

array([100, 101, 102, 103])

In [56]:
l = [0, 1, 2, 3]

In [57]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [58]:
a = np.arange(4)

In [59]:
a

array([0, 1, 2, 3])

In [60]:
b = np.array([10, 10, 10, 10])

In [61]:
b

array([10, 10, 10, 10])

In [62]:
a + b

array([10, 11, 12, 13])

In [63]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [64]:
a = np.arange(4)

In [65]:
a

array([0, 1, 2, 3])

In [66]:
a[[0, -1]]

array([0, 3])

In [67]:
a[[True, False, False, True]]

array([0, 3])

In [68]:
a >= 2

array([False, False,  True,  True])

In [69]:
a[a >= 2]

array([2, 3])

In [70]:
a.mean()

1.5

In [71]:
a[a > a.mean()]

array([2, 3])

In [72]:
a[~(a > a.mean())]

array([0, 1])

In [73]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [74]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [75]:
A = np.random.randint(100, size=(3, 3))

In [76]:
A

array([[88, 47, 63],
       [ 0, 80, 87],
       [80, 60, 71]])

In [77]:
A[np.array([
    [True, False, True],
    [True, False, True],
    [True, False, True]
])]

array([88, 63,  0, 87, 80, 71])

In [78]:
A > 30

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [79]:
A[A > 0]

array([88, 47, 63, 80, 87, 80, 60, 71])

# Linear Algebra

In [80]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [81]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [82]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [83]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [84]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

In [85]:
# An integer in python is > 24 bytes
sys.getsizeof(1)

28

In [87]:
# Longs are even larger
sys.getsizeof(10 ** 100)

72

In [90]:
# Numpy size is much smaller
print(np.dtype(int).itemsize)
print(np.dtype(np.int8).itemsize)
print(np.dtype(float).itemsize)

4
1
8


In [91]:
# One element list
print(sys.getsizeof([1]))
print(np.array([1]).nbytes)

64
4


In [101]:
# Performance
l = list(range(10000))
a = np.arange(10000)

In [102]:
%time np.sum(a ** 2)

Wall time: 998 µs


-1724114088

In [103]:
%time sum([x ** 2 for x in l])

Wall time: 1.97 ms


333283335000

# Useful Numpy Functions

In [106]:
# random
print(np.random.random(size=2))
print(np.random.normal(size=2))
print(np.random.rand(2, 4))

[0.97451965 0.57073132]
[0.49817821 0.96864968]
[[0.41806902 0.45137166 0.44275979 0.53538235]
 [0.20625334 0.07451304 0.65464807 0.45275944]]


In [108]:
# arange
print(np.arange(10))
print(np.arange(5, 10))
print(np.arange(0, 1, .1))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [109]:
# reshape
print(np.arange(10).reshape(2, 5))
print(np.arange(10).reshape(5, 2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [112]:
# linspace
print(np.linspace(0, 1, 5))
print(np.linspace(0, 1, 20))
print(np.linspace(0, 1, 20, False))

[0.   0.25 0.5  0.75 1.  ]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


In [114]:
# zeros, ones, empty
print(np.zeros(5))
print(np.zeros((3, 3)))
print(np.zeros((3,3), dtype=np.int))
print(np.ones(5))
print(np.ones((3, 3)))
print(np.empty(5))
print(np.empty((2, 2)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]
[[0.25 0.5 ]
 [0.75 1.  ]]


In [119]:
# identity and eye
print(np.identity(3))
print(np.eye(3, 3))
print(np.eye(8, 4))
print(np.eye(8, 4, k = 1))
print(np.eye(8, 4, k = -3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
